Exam/Exam.Web/Areas/Admin/Controllers/QuestionController.cs
using Exam.Core.Service;
using Exam.Model.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Net;
using twitterClone.Models;

namespace Exam.Web.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class QuestionController : Controller
    {
        private readonly ICoreService<Question> _questionService;
        private readonly IWebHostEnvironment _env;

        public QuestionController(ICoreService<Question> questionService, IWebHostEnvironment env)
        {
            _questionService = questionService;
            _env = env;
        }

        public IActionResult Index()
        {
            return View(_questionService.GetAll());
        }

        public IActionResult Delete(Guid id)
        {
            _questionService.Remove(_questionService.GetById(id));
            return RedirectToAction("Index");
        }

        public IActionResult Activate(Guid id)
        {
            _questionService.Active(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return View(HttpStatusCode.BadRequest);
            }
            var question = _questionService.GetById(id.GetValueOrDefault());
            if (question == null)
            {
                return View(HttpStatusCode.NotFound);
            }
            return View(question);
        }

        public IActionResult Update(Guid? id)
        {
            if (id == null)
            {
                return View(HttpStatusCode.BadRequest);
            }
            var question = _questionService.GetById(id.GetValueOrDefault());
            if (question == null)
            {
                return View(HttpStatusCode.NotFound);
            }
            return View(question);
        }

        [HttpPost]
        public IActionResult Update(Question question)
        {
            if (ModelState.IsValid)
            {
                Question updated = _questionService.GetById(question.ID);
                updated.Content = question.Content;
                updated.Answer = question.Answer;
                updated.Status = question.Status;

                bool result = _questionService.Update(updated);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = "Güncelleme sırasında bir hata oluştu.";
                }

            }
            else
            {
                TempData["Message"] = "İşlem başarısız oldu. Lütfen tüm alanları kontol edin.";
            }
            return View(question);
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Question question, List<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                var upload = new Upload();
                //Question Image
                bool imgResult;
                string imgPath = upload.ImageUpload(files, _env, out imgResult);
                if (imgResult)
                {
                    question.Content = imgPath;
                }
                else
                {
                    ViewBag.Message = imgPath;
                    return View(question);
                }
                bool result = _questionService.Add(question);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = $"Kayıt işlemi sırasında bir hata oluştu. " +
                        $"Lütfen tüm alanları kontrol edip tekrar deneyin.";
                }
            }
            else
            {
                TempData["Message"] = $"İşlem başarısız oldu.";
            }
            return View(question);
        }

    }
}

Exam/Exam.Web/Areas/Admin/Controllers/StudentController.cs
using Exam.Core.Service;
using Exam.Model.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Net;
using twitterClone.Models;

namespace Exam.Web.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class StudentController : Controller
    {
        private readonly ICoreService<Student> _studentService;
        private readonly IWebHostEnvironment _env;

        public StudentController(ICoreService<Student> studentService, IWebHostEnvironment env)
        {
            _studentService = studentService;
            _env = env;
        }

        public IActionResult Index()
        {
            return View(_studentService.GetAll());
        }

        public IActionResult Delete(Guid id)
        {
            _studentService.Remove(_studentService.GetById(id));
            return RedirectToAction("Index");
        }

        public IActionResult Activate(Guid id)
        {
            _studentService.Active(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return View(HttpStatusCode.BadRequest);
            }
            var student = _studentService.GetById(id.GetValueOrDefault());
            if (student == null)
            {
                return View(HttpStatusCode.NotFound);
            }
            return View(student);
        }

        public IActionResult Update(Guid? id)
        {
            if (id == null)
            {
                return View(HttpStatusCode.BadRequest);
            }
            var student = _studentService.GetById(id.GetValueOrDefault());
            if (student == null)
            {
                return View(HttpStatusCode.NotFound);
            }
            return View(student);
        }

        [HttpPost]
        public IActionResult Update(Student student)
        {
            if (ModelState.IsValid)
            {
                Student updated = _studentService.GetById(student.ID);
                updated.Name = student.Name;
                updated.Class = student.Class;
                updated.Department = student.Department;
                updated.Email = student.Email;
                updated.Password = student.Password;
                updated.isAdmin = student.isAdmin;
                updated.Phone = student.Phone;
                updated.Status = student.Status;
                updated.ProfileImageURL = student.ProfileImageURL;

                bool result = _studentService.Update(updated);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = "Güncelleme sırasında bir hata oluştu.";
                }

            }
            else
            {
                TempData["Message"] = "İşlem başarısız oldu. Lütfen tüm alanları kontol edin.";
            }
            return View(student);
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Student student, List<IFormFile> files)
        {
            if (ModelState.IsValid)
            {
                var upload = new Upload();
                //Avatar
                bool imgResult;
                string imgPath = upload.ImageUpload(files, _env, out imgResult);
                if (imgResult)
                {
                    student.ProfileImageURL = imgPath;
                }
                else
                {
                    ViewBag.Message = imgPath;
                    return View(student);
                }
                bool result = _studentService.Add(student);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = $"Kayıt işlemi sırasında bir hata oluştu. " +
                        $"Lütfen tüm alanları kontrol edip tekrar deneyin.";
                }
            }
            else
            {
                TempData["Message"] = $"İşlem başarısız oldu.";
            }
            return View(student);
        }
    }
}

Exam/Exam.Web/Controllers/MainPageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exam.Web.Controllers
{
    public class MainPageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Exam/Exam.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE HTML>
<html class="no-js" lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!--Türkçe karakter desteği için.-->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" /> <!--Görüntüleme-->
    <title>Admin Panel</title>
    <meta name="robots" content="noindex, follow" /> <!--Web tarafındaki robotlar, Google, Yandex vs Indexleyici robotlar. Yönetici panelimizi indexlememizi istemeyiz.-->
    <meta name="description" content="" /> <!--Indexlenmeyeceği için description a gerek yok.-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <!--CSS'ler-->
    <!--Favicon-->
    <link href="~/favicon.svg" rel="shortcut icon" type="image/x-icon" />
    <link rel="stylesheet" href="~/admin/assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="~/admin/assets/css/vendor/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/admin/assets/css/vendor/font-awesome.min.css">
    <link rel="stylesheet" href="~/admin/assets/css/vendor/themify-icons.css">
    <link rel="stylesheet" href="~/admin/assets/css/vendor/cryptocurrency-icons.css">
    <link rel="stylesheet" href="~/admin/assets/css/plugins/plugins.css">
    <link rel="stylesheet" href="~/admin/assets/css/helper.css">s
    <link rel="stylesheet" href="~/admin/assets/css/style.css">
    <link id="cus-style" rel="stylesheet" href="~/admin/assets/css/style-primary.css">
</head>
<body>
    <div class="main-wrapper">
        <div class="header-section">
            <div class="container-fluid">
                <div class="row justify-content-between align-items-center">
                    <div class="header-logo col-auto">
                        <a asp-controller="MainPage" asp-action="Index" asp-area="">
                            <img src="~/images/TOGU_Logo_en.png" />
                        </a>
                    </div>
                    <div class="header-right flex-grow-1 col-auto">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-auto">
                                <div class="row align-items-center">
                                    <div class="col-auto"><button class="side-header-toggle"><i class="zmdi zmdi-menu"></i></button></div>
                                </div>
                            </div>
                            <div class="col-auto">
                                <ul class="header-notification-area">
                                    <li class="adomx-dropdown col-auto">
                                        <a class="toggle" href="#">
                                            <span class="user">
                                                <span class="avatar">
                                                    <img src="" alt="">
                                                    <span class="status"></span>
                                                </span>
                                                <span class="name"></span>
                                            </span>
                                        </a>
                                        <div class="adomx-dropdown-menu dropdown-menu-user">
                                            <div class="body">
                                                <ul>
                                                    <li><a asp-controller="Home" asp-action="Logout" asp-area=""><i class="zmdi zmdi-account"></i>Logout</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="side-header show">
            <button class="side-header-close"><i class="zmdi zmdi-close"></i></button>
            <div class="side-header-inner custom-scroll">
                <nav class="side-header-menu" id="side-header-menu">
                    <ul>
                        <li class="has-sub-menu"><a asp-area="Admin" asp-controller="Home" asp-action="Index"><i class="ti-home"></i> <span>Homepage</span></a></li>
                        <li><a asp-area="Admin" asp-controller="Student" asp-action="Index"><i class="fas fa-user-graduate"></i><span>Students</span></a></li>
                        <li><a asp-area="Admin" asp-controller="Question" asp-action="Index"><i class="fas fa-question"></i> <span>Questions</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
        @RenderBody()
        <div class="footer-section">
            <div class="container-fluid">
                <div class="footer-copyright text-center">
                    <p class="text-body-light">2021 &copy; All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </div>
    <!--Scripler-->
    <script src="~/admin/assets/js/vendor/modernizr-3.6.0.min.js"></script>
    <script src="~/admin/assets/js/vendor/jquery-3.3.1.min.js"></script>
    <script src="~/admin/assets/js/vendor/popper.min.js"></script>
    <script src="~/admin/assets/js/vendor/bootstrap.min.js"></script>
    <script src="~/admin/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/admin/assets/js/plugins/tippy4.min.js.js"></script>
    <script src="~/admin/assets/js/main.js"></script>
    <script src="~/admin/assets/js/plugins/moment/moment.min.js"></script>
    <script src="~/admin/assets/js/plugins/daterangepicker/daterangepicker.js"></script>
    <script src="~/admin/assets/js/plugins/daterangepicker/daterangepicker.active.js"></script>
    <script src="~/admin/assets/js/plugins/chartjs/Chart.min.js"></script>
    <script src="~/admin/assets/js/plugins/chartjs/chartjs.active.js"></script>
    <script src="~/admin/assets/js/plugins/vmap/jquery.vmap.min.js"></script>
    <script src="~/admin/assets/js/plugins/vmap/maps/jquery.vmap.world.js"></script>
    <script src="~/admin/assets/js/plugins/vmap/maps/samples/jquery.vmap.sampledata.js"></script>
    <script src="~/admin/assets/js/plugins/vmap/vmap.active.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>