Exam/Exam.Web/Controllers/ExamController.cs
using Exam.Core.Service;
using Exam.Model.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Exam.Web.Controllers
{
    public class ExamController : Controller
    {
        private readonly ICoreService<Question> _questionService;

        public ExamController(ICoreService<Question> questionService)
        {
            _questionService = questionService;
        }

        public IActionResult Index()
        {
            return View(_questionService.GetAll());
        }
    }
}

Exam/Exam.Web/Controllers/MainPageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exam.Web.Controllers
{
    public class MainPageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Exam/Exam.Web/Controllers/ProfileController.cs
using Exam.Core.Service;
using Exam.Model.Entities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using twitterClone.Models;

namespace Exam.Web.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ICoreService<Student> _studentService;
        public ProfileController(ICoreService<Student> studentService)
        {
            _studentService = studentService;
        }

        public IActionResult Index()
        {
            HttpContext.Request.Cookies.TryGetValue("id", out string gelen);
            var student = _studentService.GetById(Guid.Parse(gelen));
            return View(student);
        }

        [HttpPost]
        public IActionResult Update(Guid id)
        {
            HttpContext.Request.Cookies.TryGetValue("id", out string gelen);
            var student = _studentService.GetById(Guid.Parse(gelen));
            if (ModelState.IsValid)
            {
                Student updated = _studentService.GetById(student.ID);
                updated.Name = student.Name;
                updated.Class = student.Class;
                updated.Department = student.Department;
                updated.Email = student.Email;
                updated.Password = student.Password;
                updated.Phone = student.Phone;
                updated.ProfileImageURL = student.ProfileImageURL;
                bool result = _studentService.Update(updated);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = "Güncelleme sırasında bir hata oluştu.";
                }

            }
            else
            {
                TempData["Message"] = "İşlem başarısız oldu. Lütfen tüm alanları kontol edin.";
            }
            return View(student);
        }

    }
}

Exam/Exam.Web/Views/MainPage/Index.cshtml
@{
    ViewData["Title"] = "Anasayfa";
}
@{
    Layout = null;
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

    <title>Anasayfa</title>
    <!--Favicon-->
    <link href="~/favicon.svg" rel="shortcut icon" type="image/x-icon" />
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/css/mainpage.css" rel="stylesheet" />
</head>
<body>
    <a asp-action="Logout" asp-controller="Home"> <button style="float:right;" class="custom-btn btn-5"><span><i class="fas fa-sign-out-alt"></i></span></button></a>

    <a asp-action="Index" asp-controller="Profile"><button style="float:left" class="custom-btn btn-7"><span>Profil</span></button></a>
    <br /> <br /><br /><br /><br />
    <header>
        <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    </header>

    <h1>Hoşgeldiniz.</h1>
    <p>Sınava başlamak için butona tıklayınız.</p>
    <div class="frame">

        <a asp-action="Index" asp-controller="Exam">
            <button class="custom-btn btn-13">Sınava Git</button>
        </a>
        <p style="font-family: Andale Mono, monospace;">
            &copy; 2021 Her Hakkı Saklıdır.
        </p>
    </div>

</body>
</html>